
const occasions = [
  'Anniversary',
  `April Fools' Day`,
  'Best Wishes',
  'Birth Announcement',
  'Birthday',
  'Christmas',
  'Confirmation',
  'Congratulations',
  'Easter',
  'Engagement',
  'First Day at School',
  'Fourth of July',
  'Friendship',
  'Get Well',
  'Graduation',
  'Halloween',
  'Hanukkah',
  'I Miss You',
  'Love & Romance',
  `Mother's Day`,
  'Naming Day',
  'New Year',
  'Pentecost',
  'Retirement',
  'Sayings & Quotes',
  `St. Patrick's Day`,
  'Sympathy',
  'Thanksgiving',
  'Thank You',
  'Thinking of You',
  `Valentine's Day`,
  'Wedding',
];

export {
  occasions,
}